### PR TITLE
hide the IE section by default and show it if

### PR DESCRIPTION
**Pull request by ryanwoldatwork**
https://github.com/18F/analytics.usa.gov/issues/765

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
Hey @ryanwoldatwork – how do you feel about making the solution more generic? Not that we anticipate any of the other nested charts/filters failing (i.e., on 'Windows', 'International', 'United States & Territories'), but I wonder if it's just as easy and more defensive to:
* hide all nested charts by default
* pass the key into `nestChild` instead of the filter based on the key
* construct the filter within `nestChild`
* use the key in your check instead of hard-coding Internet Explorer in `nestChild`

Also, as the existing code seems to assume parent/child vars can be dereferenced if not null, wondering if you need to write as defensive code there? i.e., not have all the `[0]`, etc. checks

In any case – I've pulled down the code and verified it solves the IE problem against the live data we have for NASA and EOP 👍

**Comment by ryanwoldatwork** [comment]
@ryanhofdotgov - I feel very 👍  about a more general solution here. You solved it in pseudo code. 

I'll be able to pick this up next week. If you have that refactor locally, feel free to commit atop this, or in another branch.

Thanks for your feedback!

**Comment by ryanwoldatwork** [comment]
@ryanhofdotgov - I still had the project up 😄     
How's it look now?

**Comment by ryanhofdotgov** [comment]
Nice! There seems to be one encoding issue with the ampersand character in `United States & Territories`. When I run this PR locally vs analytics.usa.gov, just looking at `All Participating Websites`, the local version doesn't break down the territories.

I suspect maybe the 1st filter needs the ampersand escaped, but then the conditional is checking against unescaped data? Apologies for not being able to dive in deeper and provide a patch – I'm a bit swamped right now, but can always make time for a quick review.

Local:
Screen Shot 2021-01-28 at 8 51 40 AM

Production:
Screen Shot 2021-01-28 at 8 51 48 AM

**Comment by tdlowden** [comment]
Hey folks. where do we stand here? Still need the one edit w/r/t the ampersand?

**Comment by ryanhofdotgov** [comment]
@tdlowden Yeah, for the more general fix – still need something to address ampersands. If you just want to get a fix up for IE right now, then Ryan W.'s earlier commit could be merged as-is.

**Comment by ryanwoldatwork** [comment]
@ryanhofdotgov - the ampersand issue has been addressed

**Pull request merged**
