### PR TITLE
specify SVG data uri for dropdown

### PR DESCRIPTION
**Pull request by hbillings**
Fixes the issue with the dropdown arrow not appearing by placing the SVG's URI directly in the CSS.

### CODE REVIEW

**Comment by konklone** [comment]
Mind including a screenshot of the effect?

**Comment by cacraig** [comment]
This works fine, but we should probably save this SVG element to it's own file, and reference that so it's easier to manage/change. Like:
  
...  
url('../thing.svg')

**Comment by hbillings** [comment]
@konklone Whoops, apparently my GH email filter works a little _too_ well. Screenshot here.
screen shot 2016-05-13 at 1 25 54 pm

@cacraig I generated the URI from an image in `css/img/arrow-down.svg`. Mostly I did it like this just to save the HTTP request, but it's so minor compared to the weight of the page that clarity should probably win here. I'll update!

**Comment by cacraig** [comment]
Awesome. Pulled it, looks good. Merging.

**Pull request merged**
