### PR TITLE
Agency nav style improvements.

### PR DESCRIPTION
**Pull request by cacraig**
This branch moves the Agency Navigation/Dropdown list into the header (replacing the Agency Title). This reuses the space already reserved for the Agency Title. 

A step in the right direction, but I'm not 100% sold on the text color, or the select box sizing.

### CODE REVIEW

**Comment by konklone** [comment]
It looks a little off for me, visiting the homepage on a mostly-but-not-completely maximized Chrome window on my Macbook Pro:

image

**Comment by gbinal** [comment]
@cacraig - any thoughts on redressing this?

**Comment by cacraig** [comment]
@konklone @gbinal Eric is right. The CSS needs to be re-arranged a bit, and will need to scale it's width to monitor size. Should be a quick modification.

**Comment by cacraig** [comment]
Fixed, that. Also made it float off of the left div of the nav bar, instead of the right. Should scale a little better with screen size.

**Comment by konklone** [comment]
Thanks, that fixed the layout problem!

So now I see one issue, and one nit. The issue is that on Chrome, the backdrop of the dropdown when activated is not dark blue as intended, but the text is still white, and so text is invisible when not highlighted:

image


The nit is that on Firefox, the backdrop is properly dark blue when the dropdown is activated, but the arrow is scrunched and weird:
image

**Comment by cacraig** [comment]
What version of Chrome are you using? I was not able to reproduce that in the latest version. I switched over the background color to the header's blue instead of transparent. Maybe that will fix it for you. Upon further investigation, the background color of the select dropdown isn't modifiable in Chrome and Safari (should appear as gray), but it is in firefox (should appear as blue).

**Comment by konklone** [comment]
You fixed it in Chrome for me (v48 on Linux)!

image

And Firefox now looks great:

image

:+1: from me.

**Pull request merged**
