### PR TITLE
a few small edits to the api docs

### PR DESCRIPTION
**Pull request by gbinal**

### CODE REVIEW

**Comment by gbinal** [comment]
hmmmmm.... one of the checks is failing.  :/

**Comment by jmhooper** [comment]
That's not you. The timeout that waits for the docker container to build may need to be longer.

**Comment by jmhooper** [comment]
I restarted the failing build. All green now.

**Comment by gbinal** [comment]
Ah - right.  Thanks.  

All tests are 💚 .  Given your 👍, I'll go ahead and merge.

**Comment by gbinal** [comment]
_He said, not realizing that the page needed to update so it could show that @jmhooper had already merged._  🤷‍♂️

**Pull request merged**
