### PR TITLE
Fix the 404 page

### LINKED ISSUE #388: 404 page styling is off
This is what I see when I click on the 'data' link in the top right of `https://analytics.usa.gov/nuclear-regulatory-commission/` which points to `https://analytics.usa.gov/national-regulatory-commission/data/`.  I've submitted a PR which I think will fix that bug, but this 404 is a bit extreme:

screenshot 2016-06-23 15 19 22

a) font size seems bigger than necessary (moving half the copy below the page on a large display)
b) blue background doesn't extend far enough down, meaning that the bottom copy is hard to read.

I suggest a css style tweak ;-)

### PR DESCRIPTION
**Pull request by allejo**
A possible solution to the 404 page styling issues.

Fixes #388

### CODE REVIEW

**Comment by konklone** [comment]
Hi @allejo, this looks like a fine solution, and thank you very much for contributing! However, I first want to give @danellebailey an opportunity to update her PR in #397, since she submitted it just yesterday.

**Comment by allejo** [comment]
sure thing 👍

**Comment by allejo** [comment]
@konklone, I was wondering if there were any other updates regarding this

**Comment by konklone** [comment]
:+1: Thank you, @allejo!

**Pull request merged**
