### PR TITLE
Adding agencies

### PR DESCRIPTION
**Pull request by gbinal**
On hold for the moment.

### CODE REVIEW

**Comment by konklone** [comment]
@gbinal still on hold?

**Comment by gbinal** [comment]
Thanks for checking in, @konklone.  It'll be great to do this sometime later this week.

**Comment by gbinal** [comment]
I'll update when ready.

**Comment by gbinal** [comment]
FYI, I believe these travis tests are failing because my first try at adding travis was flawed.  This should be safe to merge when we have the data points live.

**Comment by jmhooper** [comment]
The base for this PR is `18-pages`. Is that intentional or should it be changed to master? If that's an accident it could explain the issue with Travis since the `18f-pages` branch does not have a Travis configuration.

**Comment by jmhooper** [comment]
From what I can tell, to add an agency in the reporter, here's the changes we'll have to make:

**Add an env to the `deploy/envs` folder**

Here is [an example](https://github.com/18F/analytics-reporter/blob/master/deploy/envs/postal-service.env). The thing I'll need for this which I don't have is a report ID for the agencies we want to add.

**Use env to generate realtime, hourly, and daily reports**

This is done in the `deploys` folder. Here's some examples of what this looks like for USPS:

- [realtime](https://github.com/18F/analytics-reporter/blob/master/deploy/realtime.sh#L164-L167)
- [hourly](https://github.com/18F/analytics-reporter/blob/master/deploy/hourly.sh#L136-L138)
- [daily](https://github.com/18F/analytics-reporter/blob/master/deploy/daily.sh#L159-L162)

[Here's](https://github.com/18F/analytics-reporter/pull/163/files) a PR where we can see these changes taking place for USPS.

This is something I can move forward with as soon as I get report IDs for the agencies we wish to add, or the access necessary to get the report IDs myself.

**Comment by gbinal** [comment]
> The base for this PR is 18-pages. Is that intentional or should it be changed to master? 

Sorry about that.  You're entirely right.  This should go to `master`.

**Comment by gbinal** [comment]
Here's the report ID for EOP - 66351974.  Looks like you won't need HHS.

**Comment by jmhooper** [comment]
@gbinal: I changed the base for the PR and then rebased the commits. Now CI is green: https://travis-ci.org/18F/analytics.usa.gov/builds/191369186

**Pull request merged**
