### PR TITLE
Move 'About' section further up on page

### PR DESCRIPTION
**Pull request by onceuponatimeforever**
This UI change makes the purpose of the website clearer to new visitors.

### CODE REVIEW

**Comment by konklone** [comment]
Can you provide a screenshot of the changed layout? This will help the team visualize the change.

**Comment by onceuponatimeforever** [comment]
about_this_site_is_moved_up

**Comment by konklone** [comment]
So I'll see if anyone else wants to ring in here, but I think we're unlikely to accept this PR. This is a major visual design change, and those are generally going to get initiated and discussed within the team. In addition, I personally think this isn't the design aesthetic we're going for, even if it may have some other benefits.

**Comment by gbinal** [comment]
Agreed.  That said, we're aiming to gutcheck and possibly overhaul the design with some user-testing and fresh thinking in the next couple of months.  We should definitely factor in goals behind this PR.

**Comment by tdlowden** [comment]
+1 to @gbinal & @konklone

**Comment by konklone** [comment]
OK, closing, but thank you for the suggestion, @onceuponatimeforever, and your design feedback is always welcome!

**Pull request closed without merging**
