### PR TITLE
Add data page

### PR DESCRIPTION
**Pull request by hbillings**
This adds a link to the navbar and a page for the data feeds (removing them from the footer).  
data page

### CODE REVIEW

**Comment by konklone** [comment]
@hbillings This looks _awesome_. What do you think of adding a note at the bottom where the data used to be, at least temporarily for people used to seeing it there, linking them to the new data page?

**Comment by thekaveman** [comment]
@allejo: another interesting approach for the data file list.

(sorry to hijack the PR thread folks, just following along with your awesome work for our fork over at [analytics.smgov.net](https://github.com/CityofSantaMonica/analytics.smgov.net))

**Comment by hbillings** [comment]
Here's the current iteration of the data page:
screencapture-localhost-4000-commerce-data-1464815969223

**Comment by hbillings** [comment]
Here's the data hint in the footer:
screen shot 2016-06-03 at 11 31 44 am

**Pull request merged**
