### PR TITLE
Adding API link

### PR DESCRIPTION
**Pull request by tdlowden**

### CODE REVIEW

**Comment by konklone** [comment]
Nice! :+1:

**Comment by tdlowden** [comment]
ah dang. didn't work. what'd I do wrong?

screen shot 2018-06-21 at 2 40 48 pm

**Comment by konklone** [comment]
Ah, missing a quotation mark, I missed it in the review. I'll hotfix it.

**Comment by tdlowden** [comment]
fixing with https://github.com/18F/analytics.usa.gov/pull/511

**Pull request merged**
